### ISSUE TITLE
The page including the module bug sometimes (but not always)

### ISSUE THREAD

**Issue by cat1910** [Tazzios/cblistmodule#11] opened 2023-11-13 12:08 UTC
I've installed the module on a Joomla 4.4.0 site, CB 2.8.2, php 8.1.23.

Sometimes, but not always, the page does not load, and this error message is given :  1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Azur'' at line 1

Could you help ?
Thanks
Catherine

**Comment by Tazzios** [comment] 2023-11-13 13:19
The users that you show vary i assume?, probably a user has something strange in the fields which i do not expect. 
Does Azur has an ' in the name or an user or does another field contains a ' in the results?

**Comment by cat1910** [comment] 2023-11-15 08:03
OK yes I understand, there's a CB Field including a ' (Côte d'Azur), I've deleted the ' and will see if the problem disappears.
Thanks !
Catherine

**Comment by Tazzios** [comment] 2023-11-15 08:54
If i put 'Côte d'Azur' in a field i keeps working but let me know your findings. Maybe the problem is some where else.

**Comment by cat1910** [comment] 2023-11-16 08:36
I've deleted the ' in drop-down list type cb field. One of the value was "côte d'azur" and I've updated the value in the profiles concerned. I think the module works fine now and the problem disappeared.

**Comment by Tazzios** [comment] 2023-12-09 10:15
Fixed with [comment](https://github.com/Tazzios/cblistmodule/commit/914e3854867065fa8af1572840331bbbdfc88cc7) in the upcoming 3.0.5

**Closed as completed by Tazzios** 2023-12-09 10:15 UTC
Labels: bug
